### ISSUE TITLE
Support for 2021.1 Resharper

### ISSUE THREAD

**Issue by brentlyjdavid** [olsh/resharper-configuration-sense#20]
After installing 2021.1, this extension appears to no longer be in the list.  

Thanks!

**Comment by olsh** [comment]
Hi @brentlyjdavid 
I've just submitted the updated versions to the JetBrains plugins repository. The updates are usually approved within two business days.
Meanwhile, you can download the latest version here https://ci.appveyor.com/project/olsh/resharper-configuration-sense/build/artifacts
