### ISSUE TITLE
Update to 2016.2.3 gives error

### ISSUE THREAD

**Issue by octocat-mona** [olsh/resharper-configuration-sense#4]
Update completes with error:

> Execute Build Step Runnable JetBrains.Platform.VisualStudio.SinceVs10!JetBrains.Platform.VisualStudio.SinceVs10.TextControl.Markup.FormatDefinitions.Install.VsPackageEmitsVsClassificationFormatDefinitions::VsPackageEmitVsClassificationFormatDefinitions#3 has failed. The build step method JetBrains.Platform.VisualStudio.SinceVs10.TextControl.Markup.FormatDefinitions.Install.VsPackageEmitsVsClassificationFormatDefinitions::VsPackageEmitVsClassificationFormatDefinitions has thrown an exception. Exception has been thrown by the target of an invocation. Could not load file or assembly 'JetBrains.Platform.TextControl, Version=106.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' or one of its dependencies. The system cannot find the file specified.

After restarting VS the extension still seems to work, should this error be ignored?

**Comment by olsh** [comment]
Hello @kpstolk ,

Well, I didn't change any dependencies or contracts, so yeah, I suppose it should be ignored.

Thanks.

**Comment by octocat-mona** [comment]
OK, I hope that this issue doesn't appear for everybody though.
