### ISSUE TITLE
Environment Appsettings

### ISSUE THREAD

**Issue by Huntk23** [olsh/resharper-configuration-sense#5]
I had noticed the configuration sense doesn't take in account of appsettings.**environmentName**.json.

Perhaps this can be supported?

Thanks for the extension!

**Comment by olsh** [comment]
Thanks for the suggestion 👍 
I plan to add a settings window where you can choose configuration files.

**Comment by panosru** [comment]
@olsh hello! Can you let me know where exactly is the window that allows me to choose configuration files?

I have split my configuration files per domain so each domain has it's own appsettings json file in the format of `appsettings.<domain>.<environment>.json`

Thanks!

**Comment by olsh** [comment]
Hello @panosru 
The options page was implemented only in the R# version.
There is a workaround - save the settings as a team shared file to load the files in Rider too.
![image](https://user-images.githubusercontent.com/3613592/93126791-818a1a80-f6d5-11ea-940f-2f17ea8a6b4f.png)

**Comment by panosru** [comment]
Thanks for your response! Is it possible that this setting is not available for rider on mac? I can't find it.. :/

**Comment by olsh** [comment]
Yes, the UI for the settings are available only in the R# version, they aren't implemented in Rider.

**Comment by panosru** [comment]
Ah sorry, you mentioned it already, I was viewing from mobile and I placed my focus on the screenshot you posted.

In regards to the workaround you mentioned, would you be kind enough to elaborate a little bit? 

Thanks a lot!

**Comment by olsh** [comment]
You need to open the settings page in R#, add the necessary files and save settings as a 'Solution team-shared' layer﻿. 
In this case, Rider will be able to read the settings file. You can read more about the settings layers here https://www.jetbrains.com/help/resharper/Sharing_Configuration_Options.html#solution-team-shared-layer

**Comment by panosru** [comment]
Ah I see, I thought it creates some kind of a config file in .idea folder.

I tried in my windows VM to see what properties it places in sln.DotSettings file and for a demo project I created just to see the produced file I got this:

```xml
<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-storage-xaml" xmlns:wpf="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
	<s:String x:Key="/Default/Environment/ConfigurationSense/CustomConfigurationFiles/=F300DC1B_002DE643_002D4CCB_002D80EE_002DA7F840B07500_002Ff_003AAcme_002EFoo_002Esln/@EntryIndexedValue">["3D872C41-E226-45C8-89C1-9D3DBD7C73F2/f:appsettings.account.Development.json"]</s:String>
</wpf:ResourceDictionary>
```

I removed anything unrelated to Configuration Sense plugin.

My question is: Is it possible to write manually into the DotSettings file config for Configuration Sense? I see that it encodes the path and also places a GUID...

Thanks!

**Comment by panosru** [comment]
To my understanding, the GUID works only as a Key for the @EntryIndexedValue array I guess, and you also encode the file name of the sln file.

So basically, any GUID will work, but I have to encode the name of my sln file in order for it to work, am I right?

**Comment by olsh** [comment]
Well, I don't know how the settings work internally, sorry.

**Comment by panosru** [comment]
@olsh, ah ok... I thought that the encoding process was handled by the plugin.

Are there any plans to make that window available on Rider as well?

**Comment by olsh** [comment]
At the moment I don't have such plans, PRs are welcome.
