### ISSUE TITLE
IConfigurationSection - Can't find specific setting key

### ISSUE THREAD

**Issue by Huntk23** [olsh/resharper-configuration-sense#7]
Hi again,

I noticed configuration sense cannot find a "setting key" through `Microsoft.Extensions.Configuration.IConfiguration.GetSection(string key)` but it works using the configuration object indexer.

Screenshot:
![2017-08-30 15_34_17-testcore - microsoft visual studio](https://user-images.githubusercontent.com/3951241/29898148-1b3a3a10-8d99-11e7-9f91-4955c13c0461.png)

**Comment by olsh** [comment]
Hi @Huntk23,

`GetSection` works only with subsections and the indexer works with values.

For instance, we have the following JSON
```json
{
  "subsection": {
    "suboption1": "subvalue1_from_json"
  }
}
```

And this code
```csharp
// Both are correct
Configuration.GetSection("subsection");
Configuration["subsection:suboption1"];

// Both are incorrect
Configuration.GetSection("subsection:suboption1");
Configuration["subsection"];
```

Please, let me know if you have any questions or suggestions.

**Comment by NLI-KelbyHunt** [comment]
Hi @olsh 

Microsoft gave the ability to call the value property of a IConfigurationSection, doesn't that make it semantically correct at that point?

**Comment by Huntk23** [comment]
Hi @olsh 

Microsoft gave the ability to call the value property of a IConfigurationSection, doesn't that make it semantically correct at that point?

**Comment by olsh** [comment]
Hi @Huntk23,
Yes, I think you are right. Will fix this soon.
